# Generated by Django 5.1.2 on 2024-11-06 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatstoragemodel',
            name='media_name',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
