# Generated by Django 5.1.2 on 2024-11-06 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatstoragemodel_media_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatstoragemodel',
            name='media_name',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
