# Generated by Django 5.1.2 on 2024-11-06 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chatstoragemodel_media_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatstoragemodel',
            name='media',
        ),
        migrations.RemoveField(
            model_name='chatstoragemodel',
            name='media_name',
        ),
    ]
